//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sriracha.Deploy.Tasks.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonTaskResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonTaskResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sriracha.Deploy.Tasks.Common.CommonTaskResources", typeof(CommonTaskResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Local Command Line&lt;/h4&gt;
        ///&lt;table class=&quot;table table-striped&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Executable Path:&lt;/th&gt;
        ///		&lt;td class=&quot;form-inline&quot;&gt;
        ///            &lt;input type=&quot;text&quot; class=&quot;input-xxlarge&quot; ng-model=&quot;deploymentStep.taskOptions.ExecutablePath&quot; ng-disabled=&quot;!permissionVerifier.canEditComponentConfiguration(deploymentStep.projectId)&quot; /&gt;
        ///            &lt;button class=&quot;btn&quot; ng-click=&quot;browseContents(deploymentStep.taskOptions, &apos;ExecutablePath&apos;)&quot;&gt;&lt;i class=&quot;icon-folder-open&quot;&gt;&lt;/i&gt;&lt;/button&gt;
        ///        &lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocalCommandLineTaskOptionsView {
            get {
                return ResourceManager.GetString("LocalCommandLineTaskOptionsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Deploy Windows Service&lt;/h4&gt;
        ///&lt;table class=&quot;table table-striped&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;th&gt;Service Name:&lt;/th&gt;
        ///        &lt;td class=&quot;form-inline&quot;&gt;
        ///            &lt;input type=&quot;text&quot; class=&quot;input-xxlarge&quot; ng-model=&quot;deploymentStep.taskOptions.ServiceName&quot; ng-disabled=&quot;!permissionVerifier.canEditComponentConfiguration(deploymentStep.projectId)&quot; /&gt;
        ///            &lt;!--&lt;button class=&quot;btn&quot; ng-click=&quot;browseContents(deploymentStep.taskOptions, &apos;ExecutablePath&apos;)&quot;&gt;&lt;i class=&quot;icon-folder-open&quot;&gt;&lt;/i&gt;&lt;/button&gt;--&gt;
        ///        &lt;/td&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WindowsServiceTaskOptionsView {
            get {
                return ResourceManager.GetString("WindowsServiceTaskOptionsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;XML Config File &lt;/h4&gt;
        ///&lt;table class=&quot;table table-striped&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;th&gt;Template Source:&lt;/th&gt;
        ///        &lt;td&gt;
        ///            &lt;label class=&quot;radio&quot;&gt;
        ///                &lt;input type=&quot;radio&quot; ng-model=&quot;deploymentStep.taskOptions.TemplateSource&quot; value=&quot;XmlTemplate&quot; checked=&quot;checked&quot; /&gt;
        ///                XML Template (below)
        ///            &lt;/label&gt;
        ///            &lt;label class=&quot;radio&quot;&gt;
        ///                &lt;input type=&quot;radio&quot; ng-model=&quot;deploymentStep.taskOptions.TemplateSource&quot; value=&quot;File&quot;/&gt;
        ///                File in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlConfigFileTaskOptionsView {
            get {
                return ResourceManager.GetString("XmlConfigFileTaskOptionsView", resourceCulture);
            }
        }
    }
}
