using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

namespace Sriracha.Deploy.Tasks.Azure.AzureDto.AzureCloudService
{
    [XmlType("RoleInstance")]
    public class RoleInstance
    {
        public enum EnumInstanceStatus
        {
            //Indicates that the role state is currently unknown.
            RoleStateUnknown,
            //Indicates that resources are being created for a Virtual Machine.
            CreatingVM,
            //Indicates that a Virtual Machine is starting.
            StartingVM,
            //Indicates that resources are being created for a role instance.
            CreatingRole,
            //Indicates that a role instance is starting.
            StartingRole,
            //Indicates that a role instance has started and is ready to be used.
            ReadyRole,
            //Indicates that a role instance is unavailable for requests. This state is usually generated while the role is being created or stopped.
            BusyRole,
            //Indicates that a role instance is stopping.
            StoppingRole,
            //Indicates that a Virtual Machine is stopping.
            StoppingVM,
            //Indicates that a Virtual Machine is being deleted.
            DeletingVM,
            //Indicates that a Virtual Machine is not running. This is the final state of the shutdown process, and no other status messages should be received after StoppedVM.
            StoppedVM,
            //Indicates that a role instance has unexpectedly stopped or has failed to start. This status indicates that there is a problem with the role instance that is causing it to crash or preventing it from starting, and must be corrected before the role instance can be started. The InstanceStateDetails and InstanceErrorCode fields can hold information about the error that caused this state.
            RestartingRole,
            //Indicates that the role instance is not starting correctly. This status indicates that there is a problem with the role instance that prevents it from starting, and may be generated after the StartingRole status or ReadyRole status is received. The problem in the role instance must be found and corrected before the role can be started. The InstanceStateDetails and InstanceErrorCode fields can hold information about the role error that caused this state.
            CyclingRole,
            //Indicates that a role instance has failed to start. This status indicates that there is a problem with the role instance that prevents it from starting, and may be generated after the process returns StartingRole. The problem in the role must be found and corrected before the role can be started. The InstanceStateDetails and InstanceErrorCode fields can hold information about the role error that caused this state, which may be useful for identifying and debugging the problem.
            FailedStartingRole,
            //Indicates that a Virtual Machine has continually failed to start. This status is generated by Windows Azure, and does not indicate an error with the role instance. It may be generated after the StartingRole state.
            FailedStartingVM,
            //Indicates that a role instance has timed out before receiving a status message and is not responding to requests.
            UnresponsiveRole,
            //Indicates that a role instance has been stopped and all allocated resources have been released. This stops billing for the role instance. Role instances that have a status of StoppedDeallocated are only returned in the role instance list if the version is 2013-06-01 or higher. If all role instances in the deployment have a status of StoppedDeallocated, the deployment is not returned.
            StoppedDeallocated
        }

        public enum EnumPowerState
        {
            Starting,
            Started,
            Stopping,
            Stopped,
            Unknown
        }

        public string RoleName { get; set; }
        public string InstanceName { get; set; }
        public EnumInstanceStatus? InstanceStatus { get; set; }
        public string InstanceUpgradeDomain { get; set; }
        public string InstanceFaultDomain { get; set; }
        public string InstanceSize { get; set; }
        public string InstanceStateDetails { get; set; }
        public string InstanceErrorCode { get; set; }
        public string IpAddress { get; set; }
        
        [XmlArray("InstanceEndpoints")]
        public List<InstanceEndpoint> InstanceEndpointList { get; set; }

        public EnumPowerState PowerState { get; set; }
        public string HostName { get; set; }
        public string RemoteAccessCertificateThumbprint { get; set; }
    }
}
