//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sriracha.Deploy.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SrirachaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SrirachaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sriracha.Deploy.Data.SrirachaResources", typeof(SrirachaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Build @Model.Build.DisplayValue&lt;/h2&gt;
        ///
        ///&lt;table class=&quot;table table-bordered&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Project&lt;/th&gt;
        ///		&lt;td&gt;@Model.Build.ProjectName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Component&lt;/th&gt;
        ///		&lt;td&gt;@Model.Build.ProjectComponentName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Branch&lt;/th&gt;
        ///		&lt;td&gt;@Model.Build.ProjectBranchName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Version&lt;/th&gt;
        ///		&lt;td&gt;@Model.Build.Version&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Created By&lt;/th&gt;
        ///		&lt;td&gt;@Model.Build.CreatedByUserName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Created Date/Time&lt;/th&gt;
        ///		&lt;td&gt;@MMDB. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildPublishEmailView {
            get {
                return ResourceManager.GetString("BuildPublishEmailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;b&gt;The following deployment has approved:&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;table border=&quot;1&quot; width=&quot;500&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested By:&lt;/th&gt;
        ///		&lt;td&gt;@Model.DeployRequest.CreatedByUserName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployRequest.SubmittedDateTimeUtc, @Model.DisplayTimeZoneIdentifier)&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td colspan=&quot;2&quot;&gt;
        ///			&lt;a href=&quot;@Model.DeployStatusUrl&quot;&gt;Click here to view/begin this deployment&lt;/a&gt;
        ///		&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th colspa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeployApprovedEmailView {
            get {
                return ResourceManager.GetString("DeployApprovedEmailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;b&gt;The following deployment has failed:&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;table border=&quot;1&quot; width=&quot;700&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested By:&lt;/th&gt;
        ///		&lt;td&gt;@Model.DeployBatchStatus.Request.CreatedByUserName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployBatchStatus.Request.SubmittedDateTimeUtc, @Model.DisplayTimeZoneIdentifier)&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Started Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployBatchStatus.Request.Sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeployCancelledEmailView {
            get {
                return ResourceManager.GetString("DeployCancelledEmailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;b&gt;The following deployment has failed:&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;table border=&quot;1&quot; width=&quot;700&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested By:&lt;/th&gt;
        ///		&lt;td&gt;@Model.DeployBatchStatus.Request.CreatedByUserName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployBatchStatus.Request.SubmittedDateTimeUtc, @Model.DisplayTimeZoneIdentifier)&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Started Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployBatchStatus.Request.Sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeployFailedEmailView {
            get {
                return ResourceManager.GetString("DeployFailedEmailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;b&gt;The following deployment has rejected:&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;table border=&quot;1&quot; width=&quot;500&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested By:&lt;/th&gt;
        ///		&lt;td&gt;@Model.DeployRequest.CreatedByUserName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployRequest.SubmittedDateTimeUtc, @Model.DisplayTimeZoneIdentifier)&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td colspan=&quot;2&quot;&gt;
        ///			&lt;a href=&quot;@Model.DeployStatusUrl&quot;&gt;Click here to view/begin this deployment&lt;/a&gt;
        ///		&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th colspa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeployRejectedEmailView {
            get {
                return ResourceManager.GetString("DeployRejectedEmailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;b&gt;A new deployment has been requested:&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;table border=&quot;1&quot; width=&quot;500&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested By:&lt;/th&gt;
        ///		&lt;td&gt;@Model.DeployRequest.CreatedByUserName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployRequest.SubmittedDateTimeUtc, @Model.DisplayTimeZoneIdentifier)&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td colspan=&quot;2&quot;&gt;
        ///			&lt;a href=&quot;@Model.DeployStatusUrl&quot;&gt;Click here to view/approve this deployment&lt;/a&gt;
        ///		&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th colspa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeployRequestedEmailView {
            get {
                return ResourceManager.GetString("DeployRequestedEmailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;b&gt;The following deployment has started:&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;table border=&quot;1&quot; width=&quot;500&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested By:&lt;/th&gt;
        ///		&lt;td&gt;@Model.DeployRequest.CreatedByUserName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployRequest.SubmittedDateTimeUtc, @Model.DisplayTimeZoneIdentifier)&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Started Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployRequest.StartedDateTimeUtc, @Model.DisplayTime [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeployStartedEmailView {
            get {
                return ResourceManager.GetString("DeployStartedEmailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;b&gt;The following deployment has completed successfully:&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;table border=&quot;1&quot; width=&quot;700&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested By:&lt;/th&gt;
        ///		&lt;td&gt;@Model.DeployBatchStatus.Request.CreatedByUserName&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Requested Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployBatchStatus.Request.SubmittedDateTimeUtc, @Model.DisplayTimeZoneIdentifier)&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Started Date/Time:&lt;/th&gt;
        ///		&lt;td&gt;@MMDB.Shared.DateTimeHelper.FormatDateTime(@Model.DeployBatchSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeploySuccessEmailView {
            get {
                return ResourceManager.GetString("DeploySuccessEmailView", resourceCulture);
            }
        }
    }
}
